// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type BookFlightInput struct {
	FlightID   string `json:"flight_id"`
	SeatNumber int    `json:"seat_number"`
}

type Flight struct {
	ID                   string    `json:"id"`
	PlaneNumber          string    `json:"plane_number"`
	DeparturePoint       string    `json:"departure_point"`
	DestinationPoint     string    `json:"destination_point"`
	DepartureTime        time.Time `json:"departure_time"`
	EstimatedArrivalTime time.Time `json:"estimated_arrival_time"`
	RealDepartureTime    time.Time `json:"real_departure_time"`
	RealArrivalTime      time.Time `json:"real_arrival_time"`
	Status               string    `json:"status"`
	AvailableSeats       int       `json:"available_seats"`
}

type FlightID struct {
	ID string `json:"id"`
}

type FlightIDInput struct {
	ID string `json:"id"`
}

type FlightInput struct {
	ID                   string    `json:"id"`
	PlaneNumber          string    `json:"plane_number"`
	DeparturePoint       string    `json:"departure_point"`
	DestinationPoint     string    `json:"destination_point"`
	DepartureTime        time.Time `json:"departure_time"`
	EstimatedArrivalTime time.Time `json:"estimated_arrival_time"`
	RealDepartureTime    time.Time `json:"real_departure_time"`
	RealArrivalTime      time.Time `json:"real_arrival_time"`
	Status               string    `json:"status"`
	AvailableSeats       int       `json:"available_seats"`
}

type FlightList struct {
	Flights []*Flight `json:"flights"`
}

type FlightStatusInput struct {
	FlightID string `json:"flight_id"`
	Status   string `json:"status"`
}

type Plane struct {
	PlaneID     string `json:"plane_id"`
	PlaneNumber string `json:"plane_number"`
	TotalSeats  int    `json:"total_seats"`
	Status      string `json:"status"`
}

type PlaneID struct {
	ID string `json:"id"`
}

type PlaneIDInput struct {
	ID string `json:"id"`
}

type PlaneInput struct {
	PlaneID     string `json:"plane_id"`
	PlaneNumber string `json:"plane_number"`
	TotalSeats  int    `json:"total_seats"`
	Status      string `json:"status"`
}

type PlaneList struct {
	Planes []*Plane `json:"planes"`
}

type PlaneStatusInput struct {
	PlaneID string `json:"plane_id"`
	Status  string `json:"status"`
}
