output   = "models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
  dbname = "planes_db"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  schema = "public"
  blacklist = ["migrations", "other"]
  sslmode = "disable"
