FROM postgres:latest

# Copy the db.sql script to the Docker image
COPY db.sql /docker-entrypoint-initdb.d/

# Set the environment variables
# ENV POSTGRES_HOST=localhost
# ENV POSTGRES_PASSWORD=postgres

